### ISSUE TITLE
App launches with no data

### ISSUE THREAD

**Issue by 14inc** [ReactWindows/f8app#49]
The app would't login using facebook. Returns an error saying:

> Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

Neither does it display the details of the filters, schedule, Info, Maps etc. You get things like 

> No Notifications Yet

Why is this the case?

**Comment by rozele** [comment]
@14inc You'll need to follow the same instructions as for Android and iOS.  Make sure you have MongoDB set up and have run `npm start` and `npm import-data` before launching the app.  The Facebook login issue has been resolved.

**Comment by 14inc** [comment]
Thank you. I'll give this a go
