### ISSUE TITLE
In production?

### ISSUE THREAD

**Issue by ClemMakesApps** [ReactWindows/f8app#50]
Is this the same codebase as the one listed online?
https://www.microsoft.com/en-us/store/apps/f8-developer-conference/9nblggh4ntvn

**Comment by mpodwysocki** [comment]
@ClemMakesApps with the [WindowsStore branch](https://github.com/ReactWindows/f8app/tree/WindowsStore) it is, yes.

**Comment by ClemMakesApps** [comment]
Gotcha. Thanks for the fast reply!
